[build]
  command = "yarn deploy"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  CHEC_PUBLIC_KEY = "Your Chec public key (under setup/developer)"
  # For example, if you need a GitHub username:
  GITHUB_USERNAME = ""